### ISSUE TITLE
您好，DisplayRequest 184行有个打印日志的错误

### ISSUE THREAD

**Issue by android-xiaowei** [xiaopansky/Sketch#10]
printLogE("loadCompleted", "decode failed", "bitmap recycled", "bitmapInfo: " +  错误在loadResult.getGifDrawable().getInfo());

应该是
printLogE("loadCompleted", "decode failed", "bitmap recycled", "bitmapInfo: " + RecycleBitmapDrawable.getInfo(loadResult.getBitmap(), loadResult.getMimeType()));

**Comment by xiaopansky** [comment]
是打印出来的信息不对 还是 会崩溃？

**Comment by xiaopansky** [comment]
下个版本就会修复，多谢你的反馈！祝您天天写代码无BUG！

**Comment by xiaopansky** [comment]
此BUG已在2.3.0版本修复
