### ISSUE TITLE
您好，有的图片为什么不会缓存的，我看您的demo里面的明星图片可以缓存

### ISSUE THREAD

**Issue by android-xiaowei** [xiaopansky/Sketch#11]
您好，有的图片为什么不会缓存的，我看您的demo里面的明星图片可以缓存，我替换了几个图片url，断网以后，我替换的图片被清除了，其他的图片正常从diskcache展示了

**Comment by android-xiaowei** [comment]
[http://image.android.dianru.com/upload/ads/20150205/14230991962006154502.jpg](url)
这个url的图片，联网以后是缓存到disk了，当我清理应用以后，断网的话，disk缓存就没了

**Comment by android-xiaowei** [comment]
`    private static void deleteIfExists(File file) throws IOException {
//        try {
//            Libcore.os.remove(file.getPath());
//        } catch (ErrnoException errnoException) {
//            if (errnoException.errno != OsConstants.ENOENT) {
//                throw errnoException.rethrowAsIOException();
//            }
//        }
        if (file.exists() && !file.delete()) {
            throw new IOException();
        }
    }`

## 把这个方法注释掉以后就好了，难道这个url图会被标为脏数据吗？能帮忙解释一下么，谢谢

**Comment by xiaopansky** [comment]
你说的清理应用是清理了应用的数据还是最近任务里的？

**Comment by android-xiaowei** [comment]
清理最近任务

**Comment by xiaopansky** [comment]
努力了半天，终于发现了原因。我猜你的操作顺序应该是显示出你要的那张图片之后立马就清理APP了，如果你再显示一下别的图片（再触发一次从网络下载的过程）然后再清理APP，这时候在断网情况下就能从磁盘缓存中显示你要的那张图片了，可以概括为最后下载的图片，其磁盘缓存不能使用。究其原因就是DiskLruCache会先在内存中记录所有缓存的操作记录，恢复的时候根据操作记录判断缓存是否可用。但是在commit的时候DiskLruCache并没有立马将操作记录保存到本地，这时候如果你清理了App，那么对最后一条缓存的commit记录就丢失了，最终导致缓存不能使用。如果再次触发一次从网络下载的过程就会执行到DiskLruCache的edit方法，这个方法会触发一次将内存中的操作记录保存到本地的处理。具体的细节你可以看下DiskLruCache的源码，看DiskLruCache是怎么判断一个缓存能否使用的。最后非常感谢你使用Sketch，下个版本我会修复这个BUG，再次感谢！祝您工作愉快！

**Comment by xiaopansky** [comment]
你也可以自己改一下试试效果，你只需在DiskLruCache的651和657行后面加上都加journalWriter.flush();即可

**Comment by android-xiaowei** [comment]
感谢您，还是要想你们这些大牛学习，具有开源精神，也是我要学习的地方

**Comment by xiaopansky** [comment]
此BUG已在2.3.0正式版修复
