### ISSUE TITLE
Provide a English version of the README.md

### ISSUE THREAD

**Issue by brunodles** [xiaopansky/Sketch#12]
Hey, I'm Brazilian we speak portugese here, I saw your lib on Android Arsenal, but I dont know Chinese, can you provide at least a translated README.md file, I believe that a lot of people would use your lib.
Cya

**Comment by xiaopansky** [comment]
OK, thank you for your attention, is being translated!

**Comment by xiaopansky** [comment]
Hello, I have used Google Translate to translate the README, but the rest of the time I do not have time to translate, follow-up will make up, you can try to use Google Translate, sorry!
