### ISSUE TITLE
1 预览图片可以单击关闭吗  双击放大可以     2,加载长图可以默认加载不压缩的图片吗

### ISSUE THREAD

**Issue by chenlindaydayup** [xiaopansky/Sketch#17]

**Comment by xiaopansky** [comment]
第一个问题你可以通过ImageZoomer.setOnViewTapListener()监听单击事件然后关闭页面，第二个问题Sketch默认会根据ImageView的宽高或屏幕的宽高作为maxSize来压缩图片，如果默认不压缩的话碰见较大的内存不够用直接就崩了，如果你可以保证不会有太大的图片，那么你可以主动设置一个超大的maxSize完整的读取图片

**Comment by chenlindaydayup** [comment]
微博长图 刚进来就想显示比较清楚点  这样怎么做？

**Comment by xiaopansky** [comment]
开启分块显示超大图功能并开启手势缩放功能里的阅读模式 文档链接在readme最下方可以找到

**Comment by chenlindaydayup** [comment]
SketchImageView imageView=	new SketchImageView(mContext);
							imageView.setSupportZoom(true);
							imageView.setSupportLargeImage(true);
							imageView.setScaleType(ScaleType.FIT_XY);
							DisplayOptions displayOptions = new DisplayOptions();
							ImageZoomer imageZoomer = imageView.getImageZoomer();
							imageZoomer.setZoomable(false);

							displayOptions.setDecodeGifImage(true);
							imageView.getOptions()
									.setDecodeGifImage(true);

//							ImageSizeCalculator imageSizeCalculator=	new ImageSizeCalculator();
//							imageSizeCalculator.canUseReadModeByHeight(bmwidth,bmHeihet);
							imageZoomer.setReadMode(true);
//							Sketch.with(mContext).getConfiguration().setImageSizeCalculator(imageSizeCalculator);


							Sketch.with(mContext).display(strArray[i], imageView)
									.displayer(new TransitionImageDisplayer())
									.commit();


							linAdd.addView(imageView,new LayoutParams(screenWidth,(int)(bili*screenWidth)));

**Comment by chenlindaydayup** [comment]
这样显示的还是比较模糊

**Comment by chenlindaydayup** [comment]
这样设置错了吗？

**Comment by xiaopansky** [comment]
你用的是beta1版本吗？

**Comment by chenlindaydayup** [comment]
2 版本

**Comment by chenlindaydayup** [comment]
linAdd.addView(imageView,new LayoutParams(screenWidth,(int)(bili*screenWidth)));  这个我设置match后只能显示一部分

**Comment by chenlindaydayup** [comment]
好像是和scrollView冲突了吧

**Comment by xiaopansky** [comment]
你进QQ群交流群沟通吧这样方便，群号：529630740
