### ISSUE TITLE
gif & network layer

### ISSUE THREAD

**Issue by asker517** [xiaopansky/Sketch#18]
非常棒的图片加载库,但是看了下网络请求图片层用的是`HttpClient`实现的,考虑到Android后续已经不支持`HttpClient`,可否替换为其他类似`okHTTP`之类的加载;另外一个问题是,在加载gif动图的时候例如在列表中加载gif,并且设置都能动的情况,可否实现滚出屏幕之后动图能暂停,用户可见的时候,在继续播放这样的功能呢?

**Comment by xiaopansky** [comment]
第一个问题，低版本采用httpclient，高版本是httpurlconnection，如果你想使用okhttp，可以自定义一个HttpStack，然后通过Sketch.with(context).getConfiguration().setHttpStack(HttpStack)使用即可，Sketch本着没有过多依赖的原则没有提供默认的实现，但是也不难，你参考一下内置的HurlStack即可。

第二个问题，在列表里直接开启解码GIF即可，能够自动根据情况暂停以及恢复播放

**Comment by asker517** [comment]
@xiaopansky so ga~ thank you ! almost perfectly!
