### ISSUE TITLE
Enhancement: Adding zooming feature

### ISSUE THREAD

**Issue by skadyrov** [xiaopansky/Sketch#2]
Hi,

First of all, thank you for the amazing library! I implemented it in my photoalbum app, it is working great now!

I have a suggestion for this library: Are you thinking of adding a zooming feature? I found this nice library - [Scale Image View] (https://github.com/davemorrissey/subsampling-scale-image-view) on Github for zooming images. What do you think?

**Comment by xiaopansky** [comment]
Hi, excited to tell you that Sketch has added gesture zoom and similar oversysing of SubsampleingScaleImageView in version 2.3.0
