### ISSUE TITLE
Sketch.with().load()方式加载不支持 图片圆角吗？

### ISSUE THREAD

**Issue by Invinciblelee** [xiaopansky/Sketch#21]

**Comment by xiaopansky** [comment]
支持的。
现在实现圆角有两种方式，一种是解码是通过RoundRectImageProcessor实现，支持load和display；另一种是绘制时通过RoundRectImageShaper实现，只支持display

**Comment by Invinciblelee** [comment]
哦哦，没看到RoundRectImageProcessor
