### ISSUE TITLE
宽高比

### ISSUE THREAD

**Issue by Jvr0771** [xiaopansky/Sketch#22]
可以设置宽高比来显示图片吗

**Comment by xiaopansky** [comment]
你可以使用reszie功能修改图片的尺寸，可以让图片的宽高比跟resiz的宽高比一致，这样是会裁剪图片的

**Comment by Jvr0771** [comment]
en，这个可以，还以为可以像Fresco那样设置宽高比就方便很多，然后就可以抛弃fresco了，哈哈

**Comment by xiaopansky** [comment]
fresco不好用吗？你感觉哪些地方不好用？
