### ISSUE TITLE
IllegalArgumentException:pointerIndex out of range

### ISSUE THREAD

**Issue by XiaoQiWen** [xiaopansky/sketch#29]
你好，很喜欢这个库,使用过程中容易出现下面这个错误
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1

**Comment by XiaoQiWen** [comment]
我是嵌套在viewpager中容易出现

**Comment by asker517** [comment]
@XiaoQiWen maybe you should see [WIKI](https://github.com/xiaopansky/sketch/blob/master/docs/wiki/zoom.md)  first, at the page end.
