### ISSUE TITLE
加载图片的时候能设置header吗？

### ISSUE THREAD

**Issue by chenchongyu** [xiaopansky/Sketch#3]
hi xiaopansky:
    你的这个库非常好，但是我现在有一个问题，就是在加载图片的时候需要指定一个User-Agent， 我看了下你的文档好像是不支持。能否开放相关接口？

**Comment by xiaopansky** [comment]
如果你很急的话就得自定义一个下载器，但这样比较麻烦，你要是可以等的话下个版本就会改造ImageDownloader的实现，就可以扩展一个可以设置请求头的方法，下个版本最快本周末发布，最迟下周末发布

**Comment by chenchongyu** [comment]
好的！等你发布新版本！

**Comment by xiaopansky** [comment]
哥们 你这个需求是需要给所有的请求都加上一个User-Agent吗？有没有什么其它的条件？

**Comment by chenchongyu** [comment]
其实最好就是给请求的request开发addHeader接口就好！用户想自己添加什么header都可以。因为有的网络请求服务端是做了一些限定的，比如我们这个要自己指定user-agent

**Comment by xiaopansky** [comment]
那你需要根据不同的请求设置不同的User-Agent吗？或者有的请求设置有的请求不设置？

**Comment by chenchongyu** [comment]
我的目前是所有请求都设置相同的请求头

**Comment by xiaopansky** [comment]
哥们儿 Sketch已经发布新版了，可以设置User-Agent了，你只需调用Sketch.with(context).getConfiguration().getHttpStack().setUsetAgent(String)方法设置即可

**Comment by xiaopansky** [comment]
已在2.2.0上提供此功能
