### ISSUE TITLE
图片变小的问题

### ISSUE THREAD

**Issue by snailrobert** [xiaopansky/Sketch#4]
近日加入新的工作组，图片加载方面用到了你的Sketch，我想用它的本意是支持Gif和图片加工等原因。不过在使用中，我遇到了如下问题。当我图片URL的地址不可用时，图片列表页面就会展示默认图，这没有问题。但是，假设点击图片Item进入到详情再返回至本页时默认图片就会很神奇的缩小到左上角一块。可能点击一张默认图片Item不会复现，可是多点击几个Item就会出现如上问题。如果您有空，请不吝解答一下。我的猜测是当加载默认图片drawable时，当加载多张旧图（缓存）时scaleType的设置有问题。谢谢。

**Comment by xiaopansky** [comment]
感谢你们选择了Sketch，我们QQ沟通吧！我的QQ：86774044

**Comment by snailrobert** [comment]
非常感谢xiaopansky的帮助，帮我定位到了问题。将scaleType由fitXY改成centerCrop就可解决。

**Comment by xiaopansky** [comment]
此BUG已在2.3.0正式版中修复

**Comment by Pluckypan** [comment]
![3](https://user-images.githubusercontent.com/12028060/46723839-5a39a000-ccab-11e8-8187-b1c9a1a6c246.gif)
@panpf  最新版本2.6.1 该现象仍然会存在

**Comment by panpf** [comment]
进群沟通
